### ISSUE TITLE
Convert a ROS2 message into a protobuf message

### ISSUE THREAD

**Issue by LastStarDust** [ammarhusain/ros-protobuf-bridge#5]
Hello.
@ammarhusain 
Thank you for making this project available to the public.

I would like to know if it couldbe useful to convert a standard ROS2 message into a protobuf message in C++ on the fly.

By leveraging the [rosidl_typesupport_protobuf](https://github.com/eclipse-ecal/rosidl_typesupport_protobuf) package, I am already able to automatically generate a `.proto` definition file that perfectly matches the original `.msg` file.

Thank you

**Comment by ammarhusain** [comment]
I haven't played around much with ROS2 but I can see the value in it

**Comment by LastStarDust** [comment]
After [some discussion](https://github.com/eclipse-ecal/rosidl_typesupport_protobuf/issues/21) with the developers of [rosidl_typesupport_protobuf](https://github.com/eclipse-ecal/rosidl_typesupport_protobuf), I ended up writing a static code generator for the convertion.

**Comment by ammarhusain** [comment]
👍
